package com.egor.gmk.colors

import com.egor.gmk.GmkListData
import com.egor.gmk.R

// Data for List of each color
//GmkListData(R.drawable., "", "$"),

var green = mutableListOf(
    com.egor.gmk.GmkListData(R.drawable.aurora_polaris, "Aurora Polaris", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.baltic, "Baltic", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.british_racing_green, "British Racing Green", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.camping_r3, "Camping", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.coniferous, "Coniferous", "$150"),
    com.egor.gmk.GmkListData(R.drawable.cream_matcha, "Cream Matcha", "$126"),
    com.egor.gmk.GmkListData(R.drawable.dandy, "Dandy", "$140"),
    com.egor.gmk.GmkListData(R.drawable.deku, "Deku", "$120"),
    com.egor.gmk.GmkListData(R.drawable.fox, "Fox", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.haku, "Haku", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.hanami_dango, "Hanami Dango", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.hero, "Hero", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.lime_r2, "Lime", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.marmoreal, "Marmoreal", "$139.99"),
    com.egor.gmk.GmkListData(R.drawable.nautilus_nightmares, "Nautilus Nightmares", "$135"),
    com.egor.gmk.GmkListData(R.drawable.nuclear_data, "Nuclear Data", "$135"),
    com.egor.gmk.GmkListData(R.drawable.olive_r2, "Olive", "$180"),
    com.egor.gmk.GmkListData(R.drawable.panda, "Panda", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.poker, "Poker", "$124.99"),
    com.egor.gmk.GmkListData(R.drawable.ta_royal, "Ta Royal", "$99"),
    com.egor.gmk.GmkListData(R.drawable.terminal_r2, "Terminal", "$125"),
    com.egor.gmk.GmkListData(R.drawable.terra, "Terra", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.terror_below, "Terror Below", "$137.29"),
    com.egor.gmk.GmkListData(R.drawable.toxic, "Toxic", "$159"),
    com.egor.gmk.GmkListData(R.drawable.watermelon, "Watermelon", "$135"),
    com.egor.gmk.GmkListData(R.drawable.wavez, "Wavez", "$119.99"),
    com.egor.gmk.GmkListData(R.drawable.zooted, "Zooted", "$135")
)

var blue = mutableListOf(
    com.egor.gmk.GmkListData(R.drawable.a, "a", "$125"),
    com.egor.gmk.GmkListData(R.drawable.aero, "Aero", "$120"),
    com.egor.gmk.GmkListData(R.drawable.arabian, "Arabian Sea", "$125"),
    com.egor.gmk.GmkListData(R.drawable.astral_light, "Astral Light", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.bela, "Belafonte", "$120"),
    com.egor.gmk.GmkListData(R.drawable.bento, "Bento", "$125"),
    com.egor.gmk.GmkListData(R.drawable.blue_alert, "Blue Alert", "$125"),
    com.egor.gmk.GmkListData(R.drawable.blueple, "Blueple", "$119.99"),
    com.egor.gmk.GmkListData(R.drawable.blue_sam, "Blue Samurai", "$125"),
    com.egor.gmk.GmkListData(R.drawable.calm, "Calm Depths", "$124.99"),
    com.egor.gmk.GmkListData(R.drawable.classic_blue2, "Classic Blue", "$130.00"),
    com.egor.gmk.GmkListData(R.drawable.colbalt, "Cobalt", "$140.00"),
    com.egor.gmk.GmkListData(R.drawable.cyan, "Cyan-2D", "$160.00"),
    com.egor.gmk.GmkListData(R.drawable.deep_navy, "Deep Navy", "$125"),
    com.egor.gmk.GmkListData(R.drawable.demon, "Demon Sword", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.denim, "Denim", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.devoted, "Devoted", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.dream_bird, "Dream Bird", "$118.00"),
    com.egor.gmk.GmkListData(R.drawable.dreamtones, "Earth Tones", "$125"),
    com.egor.gmk.GmkListData(R.drawable.eclipse, "Eclipse", "$125"),
    com.egor.gmk.GmkListData(R.drawable.edc, "EDC (Every Day Carry)", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.electric, "Electric", "$109.00"),
    com.egor.gmk.GmkListData(R.drawable.evil, "Evil Eye", "$129.00"),
    com.egor.gmk.GmkListData(R.drawable.finer, "Finer Things", "$135"),
    com.egor.gmk.GmkListData(R.drawable.firefly, "Firefly", "$119.99"),
    com.egor.gmk.GmkListData(R.drawable.galaxy, "Galaxy", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.gladiator, "Gladiator", "$129.00"),
    com.egor.gmk.GmkListData(R.drawable.godspeed, "GodSpeed", "$125"),
    com.egor.gmk.GmkListData(R.drawable.hammerhead, "HammerHead", "$125.00"),
    com.egor.gmk.GmkListData(R.drawable.hydro, "Hydro", "$140.00"),
    com.egor.gmk.GmkListData(R.drawable.hyperfuse_remix, "HyperFuse Remix", "$139.00"),
    com.egor.gmk.GmkListData(R.drawable.iceberg, "Iceberg", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.indigo, "Indigo", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.inukuma, "Inukuma", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.iris, "Iris", "$169.00"),
    com.egor.gmk.GmkListData(R.drawable.keyboard_co, "Keyboard-Co", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.lazurite, "Lazurite", "$126.00"),
    com.egor.gmk.GmkListData(R.drawable.manta, "Manta", "$109.99"),
    com.egor.gmk.GmkListData(R.drawable.masterpiece, "Masterpiece", "$129.00"),
    com.egor.gmk.GmkListData(R.drawable.matrix, "Matrix 01", "$201.86"),
    com.egor.gmk.GmkListData(R.drawable.merlin, "Merlin", "$139.99"),
    com.egor.gmk.GmkListData(R.drawable.metro, "Metropolis", "$120.00"),
    com.egor.gmk.GmkListData(R.drawable.miami_pink_mods, "Miami", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.mizu, "Mizu", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.moonlight, "Moonlight", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.nautilus_r2, "Nautilus", "$115.00"),
    com.egor.gmk.GmkListData(R.drawable.nightlight, "Nightlight", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.nimbus, "Nimbus", "$129.00"),
    com.egor.gmk.GmkListData(R.drawable.noel, "Noel", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.oni, "Oni", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.pacific, "Pacific", "$125.00"),
    com.egor.gmk.GmkListData(R.drawable.phosphorus, "Phosphorous", "$129.00"),
    com.egor.gmk.GmkListData(R.drawable.pink_navy, "Pink on Navy", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.prussian, "Prussian Blue", "$135"),
    com.egor.gmk.GmkListData(R.drawable.pulse, "Pulse", "$125"),
    com.egor.gmk.GmkListData(R.drawable.retrocast, "Retrocast", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.rudy, "Rudy", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.shadow, "Shadow", "$144.99-$154.99"),
    com.egor.gmk.GmkListData(R.drawable.shark, "Shark Bait", "$144.99"),
    com.egor.gmk.GmkListData(R.drawable.shoko, "Shoko", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.shorebound, "Shorebound", "$140.00"),
    com.egor.gmk.GmkListData(R.drawable.signal, "Signal", "$129"),
    com.egor.gmk.GmkListData(R.drawable.solarized, "Solarized Dark", "$135"),
    com.egor.gmk.GmkListData(R.drawable.space_blue, "Space Cadet (blue base)", "$125"),
    com.egor.gmk.GmkListData(R.drawable.stargaze, "Stargaze", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.striker, "Striker", "$110.00"),
    com.egor.gmk.GmkListData(R.drawable.sunset_orangemod, "Sunset Surfing", "$149.99"),
    com.egor.gmk.GmkListData(R.drawable.track, "Trackday", "$130"),
    com.egor.gmk.GmkListData(R.drawable.triumph, "Triumph Adler 90", "$169.99"),
    com.egor.gmk.GmkListData(R.drawable.true_oliv, "True Olivetti", "$180.00"),
    com.egor.gmk.GmkListData(R.drawable.umbra, "Umbra", "$145.00"),
    com.egor.gmk.GmkListData(R.drawable.uniqey, "Uniqey Blue", "$140"),
    com.egor.gmk.GmkListData(R.drawable.universe, "Universe", "$125"),
    com.egor.gmk.GmkListData(R.drawable.voyage, "Voyage", "$123.99"),
    com.egor.gmk.GmkListData(R.drawable.white_blue, "White-Blue", "$136"),
    com.egor.gmk.GmkListData(R.drawable.yeeti, "Yeeti", "$139.99"),
    com.egor.gmk.GmkListData(R.drawable.yuri_orangemod, "Yuri", "$120.00"),
    com.egor.gmk.GmkListData(R.drawable.zen, "Zen Pond", "$125.00"),
)

var black = mutableListOf(
    com.egor.gmk.GmkListData(R.drawable.cyrillic_wob, "Cyrillic WoB/Beige", "$119.99"),
    com.egor.gmk.GmkListData(R.drawable.dark, "Dark", "$120"),
    com.egor.gmk.GmkListData(R.drawable.demonic, "Demonic", "$139.00"),
    com.egor.gmk.GmkListData(R.drawable.drac, "Dracula", "$114.99"),
    com.egor.gmk.GmkListData(R.drawable.exent, "Exent", "N/A"),
    com.egor.gmk.GmkListData(R.drawable.greyonblk, "Grey on Black", "$125.00"),
    com.egor.gmk.GmkListData(R.drawable.gris, "Griseann", "$129.07"),
    com.egor.gmk.GmkListData(R.drawable.highvolt, "High Voltage", "$149.99"),
    com.egor.gmk.GmkListData(R.drawable.jis, "JIS", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.lux, "Lux", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.miami_nights, "Miami Nights", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.nightrunner, "Night Runner", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.noire, "Noire", "$140.00"),
    com.egor.gmk.GmkListData(R.drawable.originative, "Originative", "$115.00"),
    com.egor.gmk.GmkListData(R.drawable.originative_cyrillic, "Originative Cyrillic", "$199.00"),
    com.egor.gmk.GmkListData(R.drawable.originative_japanese, "Originative Japanese", "$199.00"),
    com.egor.gmk.GmkListData(R.drawable.pharaoh, "Pharaoh", "$124.00"),
    com.egor.gmk.GmkListData(R.drawable.pixel, "Pixel", "$120"),
    com.egor.gmk.GmkListData(R.drawable.power, "Power Chord", "$136"),
    com.egor.gmk.GmkListData(R.drawable.shanshui, "Shanshui", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.shashin, "Shashin", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.slasher, "Slasher", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.spirit, "Spirit", "$119.99"),
    com.egor.gmk.GmkListData(R.drawable.sumi, "Sumi", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.teradrive, "TeraDrive", "$135.00"),
    com.egor.gmk.GmkListData(R.drawable.thinkcaps, "ThinkCaps", "$110"),
    com.egor.gmk.GmkListData(R.drawable.tokyo, "Tokyo Nights", "$159.00"),
    com.egor.gmk.GmkListData(R.drawable.truffelschwein, "Truffelschwein", "$127.00"),
    com.egor.gmk.GmkListData(R.drawable.vice, "Vice Nights", "$160"),
    com.egor.gmk.GmkListData(R.drawable.wasabi, "Wasabi", "$125.00"),
    com.egor.gmk.GmkListData(R.drawable.white_on_black, "White on Black", "$125.00"),
    com.egor.gmk.GmkListData(R.drawable.wob_hangul, "WoB/BoW Hangul", "$135"),
    com.egor.gmk.GmkListData(R.drawable.wob_hira, "WoB Hiragana", "$95"),
    com.egor.gmk.GmkListData(R.drawable.wob_katana, "WoB KATAKANA", "$120"),
    com.egor.gmk.GmkListData(R.drawable.wob_red, "WoB Red Cyrillic", "$130"),
)

var white = mutableListOf(
    com.egor.gmk.GmkListData(R.drawable.agent, "Agent 01", "$135"),
    com.egor.gmk.GmkListData(R.drawable.arctic, "Arctic", "$126"),
    com.egor.gmk.GmkListData(R.drawable.art, "Art", "$125"),
    com.egor.gmk.GmkListData(R.drawable.barebonestorm, "Barebones Stormtrooper", "$100"),
    com.egor.gmk.GmkListData(R.drawable.birch, "Birch", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.bleached, "Bleached", "$99.99"),
    com.egor.gmk.GmkListData(R.drawable.boho, "Boho", "$124.99"),
    com.egor.gmk.GmkListData(R.drawable.bow_hangul, "WoB/BoW Hangul", "$135"),
    com.egor.gmk.GmkListData(R.drawable.cafe, "Cafe", "$125"),
    com.egor.gmk.GmkListData(R.drawable.civil, "Civilizations", "$125"),
    com.egor.gmk.GmkListData(R.drawable.classic_bow, "Classic Black on White", "$124.99"),
    com.egor.gmk.GmkListData(R.drawable.classic_retro, "Classic Retro", "$180"),
    com.egor.gmk.GmkListData(R.drawable.deepwell, "Deepwell", "$125"),
    com.egor.gmk.GmkListData(R.drawable.delta, "Delta", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.fuji, "Fuji", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.fuyu, "Fuyu", "$149.99"),
    com.egor.gmk.GmkListData(R.drawable.grand_prix, "Grand Prix", "$125"),
    com.egor.gmk.GmkListData(R.drawable.hennessey_base, "Hennessey", "$100"),
    com.egor.gmk.GmkListData(R.drawable.honor_light, "Honor", "$95"),
    com.egor.gmk.GmkListData(R.drawable.kouhai, "Kouhai", "$135"),
    com.egor.gmk.GmkListData(R.drawable.maestro, "Maestro", "$135"),
    com.egor.gmk.GmkListData(R.drawable.metaverse, "Metaverse (w/black mods)", "$115"),
    com.egor.gmk.GmkListData(R.drawable.mika, "Mika (w/yellow mods)", "$129.00"),
    com.egor.gmk.GmkListData(R.drawable.minimal, "Minimal", "$99.99"),
    com.egor.gmk.GmkListData(R.drawable.modolight, "Modern Dolch Light", "$99.99"),
    com.egor.gmk.GmkListData(R.drawable.modern_ink, "Modern Ink", "$129.00"),
    com.egor.gmk.GmkListData(R.drawable.modern_jap, "Modern Japanese-Desko", "$135"),
    com.egor.gmk.GmkListData(R.drawable.mondrian, "Mondrian", "$79"),
    com.egor.gmk.GmkListData(R.drawable.mono, "Monochrome (w/black mods)", "$129"),
    com.egor.gmk.GmkListData(R.drawable.moomin, "Moomin", "$149.99"),
    com.egor.gmk.GmkListData(R.drawable.parcel, "Parcel", "$120"),
    com.egor.gmk.GmkListData(R.drawable.posh, "Posh (w/purple&pink mods)", "$139.99"),
    com.egor.gmk.GmkListData(R.drawable.pristine, "Pristine", "$147"),
    com.egor.gmk.GmkListData(R.drawable.redacted, "Redacted", "$124.99"),
    com.egor.gmk.GmkListData(R.drawable.seafarer, "Seafarer", "$125"),
    com.egor.gmk.GmkListData(R.drawable.soyamilk, "Soyamilk", "$130.99"),
    com.egor.gmk.GmkListData(R.drawable.tae, "Taegeukgi (w/red&blue mods)", "$142.99"),
    com.egor.gmk.GmkListData(R.drawable.mandalorian, "The-Mandalorian", "$225"),
    com.egor.gmk.GmkListData(R.drawable.trash, "Trash Friends (w/pink&black mods)", "$124.99"),
)

var red = mutableListOf(
    com.egor.gmk.GmkListData(R.drawable.b, "B", "$19.50"),
    com.egor.gmk.GmkListData(R.drawable.burgundy, "Burgundy", "$130"),
    com.egor.gmk.GmkListData(R.drawable.classic_red, "Classic Red", "$120"),
    com.egor.gmk.GmkListData(R.drawable.crimson, "Crimson Cadet", "$115"),
    com.egor.gmk.GmkListData(R.drawable.higanbana, "Higanbana", "$129"),
    com.egor.gmk.GmkListData(R.drawable.hinoko, "Hinokoku", "$149.99"),
    com.egor.gmk.GmkListData(R.drawable.infernal, "Infernal", "$135"),
    com.egor.gmk.GmkListData(R.drawable.jamon, "Jamon", "$135"),
    com.egor.gmk.GmkListData(R.drawable.led, "LedZep", "$169"),
    com.egor.gmk.GmkListData(R.drawable.lychee, "Lychee", "$130"),
    com.egor.gmk.GmkListData(R.drawable.devotion, "Magenta/Devotion", "$132"),
    com.egor.gmk.GmkListData(R.drawable.maroon, "Maroon", "$135"),
    com.egor.gmk.GmkListData(R.drawable.pepperoni, "Pepperoni", "$135"),
    com.egor.gmk.GmkListData(R.drawable.perestroika, "Perestroika", "$129"),
    com.egor.gmk.GmkListData(R.drawable.red_alert, "Red Alert", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.red_devil, "Red Devils", "$135"),
    com.egor.gmk.GmkListData(R.drawable.red_dragon, "Red Dragon", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.red_honey, "Red Honey", "$180"),
    com.egor.gmk.GmkListData(R.drawable.red_honey_cryllic, "Red Honey Cyrillic", "$199"),
    com.egor.gmk.GmkListData(R.drawable.red_sam, "Red Samurai", "$125"),
    com.egor.gmk.GmkListData(R.drawable.slasher, "Slasher", "$135"),
    com.egor.gmk.GmkListData(R.drawable.sparta, "Sparta", "$120"),
    com.egor.gmk.GmkListData(R.drawable.villanelle, "Villanelle", "$126"),
    com.egor.gmk.GmkListData(R.drawable.yugo, "Yugo", "$119"),
    com.egor.gmk.GmkListData(R.drawable.yuru, "Yuru", "$134.99")
)

var yellow = mutableListOf(
    com.egor.gmk.GmkListData(R.drawable.run, "3Run", "$125"),
    com.egor.gmk.GmkListData(R.drawable.aegyptus, "Aegyptus", "$140"),
    com.egor.gmk.GmkListData(R.drawable.cluck, "Cluck", "$135"),
    com.egor.gmk.GmkListData(R.drawable.corsa, "Corsa Auto", "N/A"),
    com.egor.gmk.GmkListData(R.drawable.feng, "FengLiSu", "$139"),
    com.egor.gmk.GmkListData(R.drawable.gregory, "Gregory", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.honey, "Honey", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.lux, "Lux", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.mika, "Mika", "$129"),
    com.egor.gmk.GmkListData(R.drawable.mudbeam, "Mudbeam", "$135"),
    com.egor.gmk.GmkListData(R.drawable.nightrunner, "Night Runner", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.penu, "Penumbra (w/ green mods)", "$170"),
    com.egor.gmk.GmkListData(R.drawable.pharaoh, "Pharaoh", "$124"),
    com.egor.gmk.GmkListData(R.drawable.serika, "Serika", "$110"),
)

var pink = mutableListOf(
    com.egor.gmk.GmkListData(R.drawable.blossom, "Blossom", "$125"),
    com.egor.gmk.GmkListData(R.drawable.daifuku, "Daifuku", "$125"),
    com.egor.gmk.GmkListData(R.drawable.darling, "Darling", "$120"),
    com.egor.gmk.GmkListData(R.drawable.haza, "Hazakura", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.hooty, "Hooty", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.jelly_delight, "Jelly Delights", "$145"),
    com.egor.gmk.GmkListData(R.drawable.ka_valentine, "KA 2019 Valentine", "$193.52"),
    com.egor.gmk.GmkListData(R.drawable.momo, "Momo Yume", "$124.99"),
    com.egor.gmk.GmkListData(R.drawable.olivia, "Olivia++", "$110"),
    com.egor.gmk.GmkListData(R.drawable.patisserie, "Patisserie", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.peach_blos, "Peach Blossom", "$129"),
    com.egor.gmk.GmkListData(R.drawable.pono, "Pono", "$124.99"),
    com.egor.gmk.GmkListData(R.drawable.star, "Star", "$145"),
    com.egor.gmk.GmkListData(R.drawable.trash, "Trash Friends", "$124.99"),
    com.egor.gmk.GmkListData(R.drawable.truffelschwein, "Truffelschwein", "$127"),
    com.egor.gmk.GmkListData(R.drawable.twilight, "Twilight", "$149.99")
)

var purple = mutableListOf(
    com.egor.gmk.GmkListData(R.drawable.alpine, "Alpine", "$139.99"),
    com.egor.gmk.GmkListData(R.drawable.alter, "Alter", "$130"),
    com.egor.gmk.GmkListData(R.drawable.amethyst, "Amethyst", "$139.99"),
    com.egor.gmk.GmkListData(R.drawable.avan, "Avanguardia", "$120"),
    com.egor.gmk.GmkListData(R.drawable.bingsu, "Bingsu", "$120"),
    com.egor.gmk.GmkListData(R.drawable.lotus, "Black Lotus", "$145"),
    com.egor.gmk.GmkListData(R.drawable.blueple, "Blueple", "$119"),
    com.egor.gmk.GmkListData(R.drawable.chaos_theory, "Chaos Theory", "$120"),
    com.egor.gmk.GmkListData(R.drawable.cojiro, "Cojiro", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.darskel, "Darskel", "$150"),
    com.egor.gmk.GmkListData(R.drawable.deep_space, "Deep Space (w/grey alphas)", "$179"),
    com.egor.gmk.GmkListData(R.drawable.drac, "Dracula", "$114.99"),
    com.egor.gmk.GmkListData(R.drawable.first_love, "First Love", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.frost, "Frost Witch", "$115"),
    com.egor.gmk.GmkListData(R.drawable.future_funk, "Future Funk", "$145"),
    com.egor.gmk.GmkListData(R.drawable.laser, "Laser", "$110"),
    com.egor.gmk.GmkListData(R.drawable.lavender, "Lavender", "$110"),
    com.egor.gmk.GmkListData(R.drawable.mecha, "Mecha 01", "$125"),
    com.egor.gmk.GmkListData(R.drawable.monarch, "Monarch", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.moon, "Moon Dust", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.nightshade, "Nightshade", "$140"),
    com.egor.gmk.GmkListData(R.drawable.phantom, "Phantom", "$145"),
    com.egor.gmk.GmkListData(R.drawable.plum, "Plum", "$119.99"),
    com.egor.gmk.GmkListData(R.drawable.purpleish, "Purple ish", "$135"),
    com.egor.gmk.GmkListData(R.drawable.q_01, "Q:01", "$149"),
    com.egor.gmk.GmkListData(R.drawable.regal, "Regal", "$140"),
    com.egor.gmk.GmkListData(R.drawable.retrotrip, "Retrotrip", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.retrowave, "Retrowave", "$130"),
    com.egor.gmk.GmkListData(R.drawable.rouge, "Rouge", "$120"),
    com.egor.gmk.GmkListData(R.drawable.serenity, "Serenity", "$125"),
    com.egor.gmk.GmkListData(R.drawable.skelly, "Skeletor", "$159"),
    com.egor.gmk.GmkListData(R.drawable.symbiote, "Symbiote", "$124.99"),
    com.egor.gmk.GmkListData(R.drawable.taro, "Taro", "$110"),
    com.egor.gmk.GmkListData(R.drawable.terror, "Terror", "$135"),
    com.egor.gmk.GmkListData(R.drawable.tuzi, "Tuzi", "$119"),
    com.egor.gmk.GmkListData(R.drawable.vaporwave, "Vaporwave", "$125"),
    com.egor.gmk.GmkListData(R.drawable.violet, "Violet on Cream", "$115"),
    com.egor.gmk.GmkListData(R.drawable.violet_tend, "Violet Tendencies", "$160"),
)

var grey_beige = mutableListOf(
    com.egor.gmk.GmkListData(R.drawable.r2_8008, "8008", "$99.99"),
    com.egor.gmk.GmkListData(R.drawable.r3_9009, "9009", "$99.99"),
    com.egor.gmk.GmkListData(R.drawable.apollo, "Apollo", "$120"),
    com.egor.gmk.GmkListData(R.drawable.arch, "Arch", "$128"),
    com.egor.gmk.GmkListData(R.drawable.ascii, "Ascii", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.ashes, "Ashes", "$130"),
    com.egor.gmk.GmkListData(R.drawable.beta, "Beta", "$138"),
    com.egor.gmk.GmkListData(R.drawable.boneyard, "Boneyard", "$120"),
    com.egor.gmk.GmkListData(R.drawable.boulder, "Boulder", "$141.99"),
    com.egor.gmk.GmkListData(R.drawable.bushido, "Bushido", "$125"),
    com.egor.gmk.GmkListData(R.drawable.cinder, "Cinder", "$135"),
    com.egor.gmk.GmkListData(R.drawable.classic_arabic, "Classic Arabic", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.classic_beige, "Classic Beige", "$125"),
    com.egor.gmk.GmkListData(R.drawable.classic_retro, "Classic Retro", "$180"),
    com.egor.gmk.GmkListData(R.drawable.classic_retro_pack, "Classic Retro 1953", "$135"),
    com.egor.gmk.GmkListData(R.drawable.cyrillic_beige, "Cyrillic Beige", "$119.99"),
    com.egor.gmk.GmkListData(R.drawable.dolch_r5, "Dolch", "$135"),
    com.egor.gmk.GmkListData(R.drawable.dolch_reborn, "Dolch Reborn", "$136"),
    com.egor.gmk.GmkListData(R.drawable.dualshot, "Dualshot", "$119.99"),
    com.egor.gmk.GmkListData(R.drawable.electric, "Electric", "$109"),
    com.egor.gmk.GmkListData(R.drawable.evil_dolch, "Evil Dolch", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.fleuriste, "Fleuriste", "$119.99"),
    com.egor.gmk.GmkListData(R.drawable.foundation, "Foundation", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.fundamentals, "Fundamentals", "$115"),
    com.egor.gmk.GmkListData(R.drawable.gmk_r3, "DMG", "$124.99"),
    com.egor.gmk.GmkListData(R.drawable.harderbeige, "Harderbeige", "$140"),
    com.egor.gmk.GmkListData(R.drawable.honeywell, "Honeywell", "$135"),
    com.egor.gmk.GmkListData(R.drawable.honeywell_co, "Honeywell-Co", "$139"),
    com.egor.gmk.GmkListData(R.drawable.honor_dark, "Honor", "$95"),
    com.egor.gmk.GmkListData(R.drawable.hooty, "Hooty", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.hyper, "HyperFuse Origins", "$159"),
    com.egor.gmk.GmkListData(R.drawable.hyper_redux, "HyperFuse Redux", "$169"),
    com.egor.gmk.GmkListData(R.drawable.jags, "Jags", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.klassiker, "Klassiker", "$119.99"),
    com.egor.gmk.GmkListData(R.drawable.lunar, "Lunar", "$160"),
    com.egor.gmk.GmkListData(R.drawable.mercury, "Mercury", "$125"),
    com.egor.gmk.GmkListData(R.drawable.miami_dusk, "Miami Dusk", "$93.35"),
    com.egor.gmk.GmkListData(R.drawable.mint_dolch, "Mint Dolch", "$159.99"),
    com.egor.gmk.GmkListData(R.drawable.moai, "Moai", "$149.99"),
    com.egor.gmk.GmkListData(R.drawable.modern_dolch, "Modern Dolch", "$99.99"),
    com.egor.gmk.GmkListData(R.drawable.momo, "Momo Yume", "$124.99"),
    com.egor.gmk.GmkListData(R.drawable.monokai, "Monokai Material", "$135"),
    com.egor.gmk.GmkListData(R.drawable.muted, "Muted", "$130"),
    com.egor.gmk.GmkListData(R.drawable.muted_retro, "Muted Retro", "$180"),
    com.egor.gmk.GmkListData(R.drawable.n6, "N6TU1-CR (40%)", "$90"),
    com.egor.gmk.GmkListData(R.drawable.nines, "Nines", "$139.99"),
    com.egor.gmk.GmkListData(R.drawable.nord, "Nord", "$125"),
    com.egor.gmk.GmkListData(R.drawable.norse, "Norse", "$119.99"),
    com.egor.gmk.GmkListData(R.drawable.ntd, "NTD", "$128"),
    com.egor.gmk.GmkListData(R.drawable.oblivion, "Oblivion", "$120"),
    com.egor.gmk.GmkListData(R.drawable.ocean, "Ocean Dolch", "$149"),
    com.egor.gmk.GmkListData(R.drawable.paperwork, "Paperwork (40%)", "$100"),
    com.egor.gmk.GmkListData(R.drawable.rainy, "Rainy Day", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.red_line, "Red Line (w/red legends)", "$104.99"),
    com.egor.gmk.GmkListData(R.drawable.sandstorm, "SandStorm", "$127"),
    com.egor.gmk.GmkListData(R.drawable.sixes, "Sixes", "$110"),
    com.egor.gmk.GmkListData(R.drawable.sky_dolch, "Sky Dolch", "$120"),
    com.egor.gmk.GmkListData(R.drawable.sky_modo, "Sky Modo", "$150"),
    com.egor.gmk.GmkListData(R.drawable.sloth, "Sloth", "$125"),
    com.egor.gmk.GmkListData(R.drawable.soware, "Soware", "$120"),
    com.egor.gmk.GmkListData(R.drawable.space, "Space Cadet", "$120"),
    com.egor.gmk.GmkListData(R.drawable.stealth, "Stealth", "$100"),
    com.egor.gmk.GmkListData(R.drawable.storm, "Storm", "$154.99"),
    com.egor.gmk.GmkListData(R.drawable.trader, "Trader", "$115"),
    com.egor.gmk.GmkListData(R.drawable.umka, "Umka", "$129"),
    com.egor.gmk.GmkListData(R.drawable.ursa, "Ursa", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.white_dark, "White Dark Grey", "$120"),
    com.egor.gmk.GmkListData(R.drawable.wild, "Wild", "$211.36")
)

var brown = mutableListOf(
    com.egor.gmk.GmkListData(R.drawable.bread, "Bread", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.chocolate, "Chocolatier", "$145"),
    com.egor.gmk.GmkListData(R.drawable.copper, "Copper", "$139.99"),
    com.egor.gmk.GmkListData(R.drawable.hanok, "Hanok", "$135"),
    com.egor.gmk.GmkListData(R.drawable.harvest, "Harvest", "$135"),
    com.egor.gmk.GmkListData(R.drawable.mint, "Mint Chocolate (w/ teal alpha)", "$119.83"),
    com.egor.gmk.GmkListData(R.drawable.tiramasu, "Tiramisu", "$127"),
)

var orange = mutableListOf(
    com.egor.gmk.GmkListData(R.drawable.carbon, "Carbon", "$159.99"),
    com.egor.gmk.GmkListData(R.drawable.charred, "Charred Orange", "$94.72"),
    com.egor.gmk.GmkListData(R.drawable.coral, "Coral", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.kaiju, "Kaiju (w/ green mods)", "$120"),
    com.egor.gmk.GmkListData(R.drawable.liftoff, "Liftoff", "$124.99"),
    com.egor.gmk.GmkListData(R.drawable.monkey, "Monkey", "$125"),
    com.egor.gmk.GmkListData(R.drawable.orange_boi, "Orange Boi", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.peaches, "Peaches-n-Cream Lite", "$110"),
    com.egor.gmk.GmkListData(R.drawable.reforged, "ReForged", "$134.99"),
    com.egor.gmk.GmkListData(R.drawable.skidolcha, "Skidolcha", "$180"),
    com.egor.gmk.GmkListData(R.drawable.skidata, "Skidata", "$145"),
)

var multi = mutableListOf(
    com.egor.gmk.GmkListData(R.drawable.analog, "Analog Dreams", "$125"),
    com.egor.gmk.GmkListData(R.drawable.awaken, "Awaken", "$120"),
    com.egor.gmk.GmkListData(R.drawable.colorchrome, "Colorchrome", "$120"),
    com.egor.gmk.GmkListData(R.drawable.diner, "Diner", "$130"),
    com.egor.gmk.GmkListData(R.drawable.dots, "Dots", "$130"),
    com.egor.gmk.GmkListData(R.drawable.froyo, "Fro.Yo", "$135"),
    com.egor.gmk.GmkListData(R.drawable.gateway, "Gateway", "$144.99"),
    com.egor.gmk.GmkListData(R.drawable.hallyu, "Hallyu", "$129.99"),
    com.egor.gmk.GmkListData(R.drawable.handarbeit, "Handarbeit & Nachtarbeit", "$120"),
    com.egor.gmk.GmkListData(R.drawable.houhai, "Houhai", "$139.99"),
    com.egor.gmk.GmkListData(R.drawable.ishtar, "Ishtar", "$144.99"),
    com.egor.gmk.GmkListData(R.drawable.matsu, "Matsu", "$140"),
    com.egor.gmk.GmkListData(R.drawable.mictlan, "Mictlan", "$99"),
    com.egor.gmk.GmkListData(R.drawable.midnight, "Midnight Rainbow", "$130"),
    com.egor.gmk.GmkListData(R.drawable.panels, "Panels", "$120"),
    com.egor.gmk.GmkListData(R.drawable.poly, "Polybius", "$135"),
    com.egor.gmk.GmkListData(R.drawable.prepress, "Prepress", "$149.99"),
    com.egor.gmk.GmkListData(R.drawable.pride, "Pride", "$142.99"),
    com.egor.gmk.GmkListData(R.drawable.rainbow, "Rainbow", "$138"),
)

 var addons = mutableListOf(

     com.egor.gmk.GmkListData(R.drawable.accent_one, "Accent Keys One (3 kits)", "$35"),
     com.egor.gmk.GmkListData(R.drawable.accent_two, "Accent Keys Two (3 kits)", "$25"),
     com.egor.gmk.GmkListData(R.drawable.beige_uwu, "Beige/WoB uwu Add-on", "$36.99"),
     com.egor.gmk.GmkListData(R.drawable.black_mod, "GMK Black Modi", "$60"),
     com.egor.gmk.GmkListData(R.drawable.ceresia, "Ceresia", "$79"),
     com.egor.gmk.GmkListData(R.drawable.cherry_logo, "Cherry Logo", "$16"),
     com.egor.gmk.GmkListData(R.drawable.cmyk, "CMYK", "$36"),
     com.egor.gmk.GmkListData(R.drawable.cmyw_new, "CMYW", "$35"),
     com.egor.gmk.GmkListData(R.drawable.unique, "GMK CUSTOM MODIFIERS", "N/A"),
     com.egor.gmk.GmkListData(R.drawable.doge, "Dogethink Novelty", "$10"),
     com.egor.gmk.GmkListData(R.drawable.bugaloo, "Electric Bluegaloo Mod", "$47"),
     com.egor.gmk.GmkListData(R.drawable.escapes, "Escape Pack V1/V2", "$13.89-$17.06"),
     com.egor.gmk.GmkListData(R.drawable.greek_beige, "Greek Beige Add-on", "$30"),
     com.egor.gmk.GmkListData(R.drawable.hyperfuse_accent, "HyperFuse Accent", "$40"),
     com.egor.gmk.GmkListData(R.drawable.korean_beige_new, "Korean Beige Add-on", "$45"),
     com.egor.gmk.GmkListData(R.drawable.leds_new, "LED", "$2.90-$3.60"),
     com.egor.gmk.GmkListData(R.drawable.magenta_dolch, "Magenta Dolch Accent", "$69"),
     com.egor.gmk.GmkListData(R.drawable.magenta, "Magenta Mods", "$45"),
     com.egor.gmk.GmkListData(R.drawable.missing, "Missing Keys", "$49"),
     com.egor.gmk.GmkListData(R.drawable.sleeves, "Mr Sleeves", "$70"),
     com.egor.gmk.GmkListData(R.drawable.ortho_addon, "N9 Ortho Add-on", "$46.99"),
     com.egor.gmk.GmkListData(R.drawable.neon, "Neon RGBY Mods", "$55"),
     com.egor.gmk.GmkListData(R.drawable.og_space, "OG Spacekeys (3 kits)", "$25"),
     com.egor.gmk.GmkListData(R.drawable.pretty, "Pretty in Pink", "$45"),
     com.egor.gmk.GmkListData(R.drawable.purp_mod, "Purple Mod", "$41"),
     com.egor.gmk.GmkListData(R.drawable.rgby_new, "RGBY", "$49"),
     com.egor.gmk.GmkListData(R.drawable.rgbyk_addon, "RGBYK Add-On", "$60"),
     com.egor.gmk.GmkListData(R.drawable.rgbyod, "RGBYOD Modifiers", "$59"),
     com.egor.gmk.GmkListData(R.drawable.sky_dolch_addon, "Sky Dolch Accent ", "$32-$39"),
     com.egor.gmk.GmkListData(R.drawable.swiss, "Swiss Addon (2 kits)", "$80"),
     com.egor.gmk.GmkListData(
         R.drawable.wob_40,
         "WoB-40s/Colevrak/R0-R5-Extensions (3 kits)",
         "$45-$55"
     ),
     com.egor.gmk.GmkListData(R.drawable.hangul_addon, "Hangul Add-on (2 kits)", "$45"),
     com.egor.gmk.GmkListData(R.drawable.wob_icon, "WoB/BoW Icon Extension", "$54.99"),
     com.egor.gmk.GmkListData(R.drawable.nordeuk, "NORDEUK Add-On (2 kits)", "$57"),
     com.egor.gmk.GmkListData(R.drawable.shine, "WOB Shinethrough", "$35"),
     com.egor.gmk.GmkListData(R.drawable.zhuyin, "Zhuyin (2 kits)", "$70"),
)



var list = arrayListOf(
    green,
    blue,
    black,
    white,
    red,
    yellow,
    pink,
    purple,
    grey_beige,
    brown,
    orange,
    multi,
    addons

)

