package com.egor.unused

import com.egor.gmk.R

// Data for detail page for each gmk set
/*
val : Array<Int> = arrayOf()
val : Array<String> = arrayOf()
val : Array<String> = arrayOf()
* */

// What i used before refactoring code base, had 3000 lines of code



var greenPic: Array<Int> = arrayOf(
    R.drawable.aurora_polaris,
    R.drawable.baltic,
    R.drawable.british_racing_green,
    R.drawable.camping_r3,
    R.drawable.coniferous,
    R.drawable.cream_matcha,
    R.drawable.dandy,
    R.drawable.deku,
    R.drawable.fox,
    R.drawable.haku,
    R.drawable.hanami_dango,
    R.drawable.hero,
    R.drawable.lime_r2,
    R.drawable.marmoreal,
    R.drawable.nautilus_nightmares,
    R.drawable.nuclear_data,
    R.drawable.olive_r2,
    R.drawable.panda,
    R.drawable.poker,
    R.drawable.ta_royal,
    R.drawable.taiga,
    R.drawable.terminal_r2,
    R.drawable.terra,
    R.drawable.terror_below,
    R.drawable.toxic,
    R.drawable.watermelon,
    R.drawable.wavez,
    R.drawable.zooted, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,


)

val greenTitle: Array<String> = arrayOf(
    "Aurora-Polaris",
    "Baltic",
    "British-Racing-Green",
    "Camping-R3",
    "Coniferous",
    "Cream-Matcha",
    "Dandy",
    "Deku",
    "Fox",
    "Haku",
    "Hanami-Dango",
    "Hero",
    "Lime-R2",
    "Marmoreal",
    "Nautilus-Nightmares",
    "Nuclear-Data",
    "Olive-R2",
    "Panda",
    "Poker",
    "TA-Royal-Alpha-610-Typewriter-R2",
    "Taiga",
    "Terminal-R2",
    "Terra",
    "Terror-Below",
    "Toxic",
    "Watermelon",
    "Wavez",
    "Zooted",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",


    )

val greenPrice: Array<String> = arrayOf(
    "Base - $134.99",
    "Base - $134.99",
    "Base - $129.99",
    "Base - $129.99",
    "Base - $150",
    "Base - $126",
    "Base - $140",
    "Base - $120",
    "Base - $134.99",
    "Base - $134.99",
    "Base - $139.99",
    "Base - $129.99",
    "Base - $134.99",
    "Base - $139.99",
    "Base - $135",
    "Base - $135",
    "Base - $180",
    "Base - $134.99",
    "Base - $124.99",
    "Base - $99",
    "Base - $128",
    "Base - $125",
    "Base - $134.99",
    "Base - $137.29",
    "Base - $159",
    "Base - $135",
    "Base - $119.99",
    "Base - $135",
    "Base - ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",

)




